import type { Subscription } from '../types';

const now = new Date();
const currentMonth = now.getMonth();
const currentYear = now.getFullYear();

export const mockSubscriptions: Subscription[] = [
  {
    id: '1',
    name: '中国移动（主卡）',
    icon: 'smartphone',
    iconColor: '#3b82f6',
    amount: 58,
    currency: 'CNY',
    billingDay: 2,
    billingCycle: 'monthly',
    category: 'telecom',
    autoRenew: true,
    isActive: true,
    notes: '5G套餐 30GB',
    createdAt: new Date(currentYear, currentMonth - 3, 1).toISOString(),
  },
  {
    id: '2',
    name: '中国移动（副卡）',
    icon: 'smartphone',
    iconColor: '#3b82f6',
    amount: 38,
    currency: 'CNY',
    billingDay: 12,
    billingCycle: 'monthly',
    category: 'telecom',
    autoRenew: true,
    isActive: true,
    notes: '流量卡 10GB',
    createdAt: new Date(currentYear, currentMonth - 2, 1).toISOString(),
  },
  {
    id: '3',
    name: 'Apple Music',
    icon: 'music',
    iconColor: '#ec4899',
    amount: 11,
    currency: 'CNY',
    billingDay: 3,
    billingCycle: 'monthly',
    category: 'entertainment',
    autoRenew: true,
    isActive: true,
    createdAt: new Date(currentYear, currentMonth - 6, 1).toISOString(),
  },
  {
    id: '4',
    name: '爱奇艺',
    icon: 'play-circle',
    iconColor: '#22c55e',
    amount: 178,
    currency: 'CNY',
    billingDay: 15,
    billingCycle: 'yearly',
    yearlyMonthDay: `${String(currentMonth + 1).padStart(2, '0')}-15`,
    category: 'entertainment',
    autoRenew: true,
    isActive: true,
    notes: '黄金VIP年卡',
    createdAt: new Date(currentYear - 1, currentMonth, 15).toISOString(),
  },
  {
    id: '5',
    name: 'ChatGPT Plus',
    icon: 'bot',
    iconColor: '#10b981',
    amount: 20,
    currency: 'USD',
    billingDay: 20,
    billingCycle: 'monthly',
    category: 'tool',
    autoRenew: true,
    isActive: true,
    createdAt: new Date(currentYear, currentMonth - 4, 1).toISOString(),
  },
  {
    id: '6',
    name: 'iCloud 50GB',
    icon: 'cloud',
    iconColor: '#6366f1',
    amount: 21,
    currency: 'CNY',
    billingDay: 28,
    billingCycle: 'monthly',
    category: 'cloud',
    autoRenew: true,
    isActive: true,
    createdAt: new Date(currentYear, currentMonth - 8, 1).toISOString(),
  },
  {
    id: '7',
    name: 'Netflix',
    icon: 'tv',
    iconColor: '#ef4444',
    amount: 9.99,
    currency: 'USD',
    billingDay: 8,
    billingCycle: 'monthly',
    category: 'entertainment',
    autoRenew: true,
    isActive: true,
    notes: 'Standard Plan',
    createdAt: new Date(currentYear, currentMonth - 5, 1).toISOString(),
  },
  {
    id: '8',
    name: 'GitHub Copilot',
    icon: 'code',
    iconColor: '#1e293b',
    amount: 10,
    currency: 'USD',
    billingDay: 18,
    billingCycle: 'monthly',
    category: 'tool',
    autoRenew: true,
    isActive: true,
    createdAt: new Date(currentYear, currentMonth - 3, 1).toISOString(),
  },
  {
    id: '9',
    name: 'Spotify',
    icon: 'headphones',
    iconColor: '#22c55e',
    amount: 15.99,
    currency: 'CNY',
    billingDay: 5,
    billingCycle: 'monthly',
    category: 'entertainment',
    autoRenew: false,
    isActive: false,
    notes: '已暂停',
    createdAt: new Date(currentYear, currentMonth - 10, 1).toISOString(),
  },
];
